apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-core-1-23
  generateName: openshift-pipelines-core-1-23-stage-rp-
  namespace: tekton-ecosystem-tenant
spec:
  releasePlan: openshift-pipelines-core-1-23-stage-rp
  snapshot: openshift-pipelines-core-1-23-20260727-030648-000
