apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-index-5-0-1-23
  generateName: openshift-pipelines-1-23-fbc-stage-rp-
  namespace: tekton-ecosystem-tenant
spec:
  releasePlan: openshift-pipelines-1-23-fbc-stage-rp
  snapshot: openshift-pipelines-index-5-0-1-23-20260727-090711-000
