apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-index-4-20-1-23
  generateName: openshift-pipelines-index-4-20-1-23-prod-rp-
  namespace: tekton-ecosystem-tenant
spec:
  releasePlan: openshift-pipelines-index-4-20-1-23-prod-rp
  snapshot: openshift-pipelines-index-4-20-1-23-20260728-230335-000
