apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-index-4-14-1-22
  generateName: openshift-pipelines-index-4-14-1-22-stage-rp-
  namespace: tekton-ecosystem-tenant
spec:
  releasePlan: openshift-pipelines-index-4-14-1-22-stage-rp
  snapshot: openshift-pipelines-index-4-14-1-22-20260803-105703-000
